apiVersion: batch/v1
kind: Job
metadata:
  name: application-set-chart-{{ randAlphaNum 8 | lower }}
spec:
  backoffLimit: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: app-dog
        image: busybox
        command: ["/bin/sh","-c","for i in {1..10}; do echo mypod is running; sleep 5; done"]
