apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1-git-1-helm-app
  namespace: argocd
  labels:
    for: jpmc
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-kt1
  sources:
    - repoURL: https://github.com/OpsMx/argo-customer-demo.git
      path: datas/git/two-git-source/git1
      targetRevision: test
    - repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'
      path: datas/helm/dubble-helm/helm2
      targetRevision: test
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
