apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-diff-sources
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-kt1
  sources:
    - repoURL: https://github.com/bitthalpatidar/argocd-task.git
      path: data/two-source/source-one
      targetRevision: HEAD
    - repoURL: https://github.com/bitthalpatidar/test-argo.git
      path: datas/git/two-git-source/git1
      targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
