{{- if .Values.deployAllApps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-suite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OpsMx/argo-customer-demo.git
    targetRevision: helm-deploy-all
    path: stack
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
{{- else }}
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-argocd-resources-{{ randAlphaNum 5 | lower }}
  namespace: argocd
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install  # Runs before upgrade and install
    "helm.sh/hook-delete-policy": hook-succeeded  # Deletes the job after it succeeds
spec:
  backoffLimit: 4  # Allow retry up to 4 times
  template:
    spec:
      serviceAccountName: default  # Ensure the job uses the default service account
      containers:
        - name: cleanup
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Deleting Argo CD applications..."
              kubectl delete applications.argoproj.io --all -n argocd 
              kubectl delete applicationsets.argoproj.io --all -n argocd 
      restartPolicy: Never
{{- end }}
