apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jpmc-test-auto
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: test
    repoURL: https://github.com/OpsMx/argo-customer-demo
    targetRevision: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
