apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "mydatabase"
  MYSQL_USER: "myuser"
  MYSQL_PASSWORD: "mypassword"
