apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-helm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitthalpatidar/test-argo.git'
    targetRevision: HEAD
    path: single-helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-task
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
