apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: single-source
spec:
  destination:
    namespace: my-test
    server: 'https://kubernetes.default.svc'
  source:
    path: single-source
    repoURL: 'https://github.com/bitthalpatidar/test-argo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
