apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-pvc-manager-role
rules:
  - apiGroups:
      - ""  # Core API group
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
