apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-pvc-manager-binding
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: bitthal-agro  # Replace with the namespace where ArgoCD is installed
roleRef:
  kind: ClusterRole
  name: argocd-pvc-manager-role  # Use the name of the ClusterRole defined above
  apiGroup: rbac.authorization.k8s.io
