apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: {{ include "postgresql.name" . }}
    chart: {{ include "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  postgresql.conf: |
    # Custom PostgreSQL configurations go here
    # For example:
    max_connections = 100
    shared_buffers = 256MB

