apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
  labels:
    app: {{ include "postgresql.name" . }}
    chart: {{ include "postgresql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgresql.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgresql.name" . }}
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"  # Use a secret in production
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "mydatabase"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: {{ .Values.persistence.accessModes | toJson }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        storageClassName: {{ .Values.persistence.storageClass }}
