apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-github-resource
spec:
  destination:
    namespace: my-task
    server: 'https://kubernetes.default.svc'
  source:
    - repoURL: https://github.com/bitthalpatidar/test-argo.git
      path: test1
      targetRevision: HEAD
    - repoURL: https://github.com/bitthalpatidar/test-argo.git
      path: test2
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
