apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: two-github-resource
  namespace: argocd
spec:
  destination:
    namespace: my-task
    server: 'https://kubernetes.default.svc'
  source:
    path: test1
    repoURL: 'https://github.com/bitthalpatidar/test-argo.git'
    targetRevision: HEAD
    path: test2
    repoURL: 'https://github.com/bitthalpatidar/test-argo.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
