apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-plugin-generator
  namespace: argocd
spec:
  generators:
    - plugin:
        name: custom-plugin-generator
        env:
          - name: ENVIRONMENT
            value: "production"
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/OpsMx/argo-customer-demo.git'
        targetRevision: test
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
