apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-plugin-script
  namespace: argocd
data:
  generate-apps.sh: |
    #!/bin/bash
    # This script generates application definitions in JSON format for Argo CD.
    
    # Start the JSON array
    echo "["
    
    # First application entry
    echo "  {"
    echo "    \"name\": \"app1\","
    echo "    \"path\": \"datas/git/two-git-source/git1\","
    echo "    \"namespace\": \"argocd-kt\""
    echo "  },"
    
    # Second application entry
    echo "  {"
    echo "    \"name\": \"app2\","
    echo "    \"path\": \"datas/git/two-git-source/git2\","
    echo "    \"namespace\": \"test\""
    echo "  }"
    
    # End the JSON array
    echo "]"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm1
  namespace: argocd
data:
  configManagementPlugins: |
    - name: custom-plugin-generator
      generate:
        command: ["/bin/bash", "plugin-generator/generate-apps.sh"]
