apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-plugin-script
  namespace: argocd
data:
  generate-apps.sh: |
    #!/bin/bash
    cat <<EOF
    [
      {
        "name": "app1",
        #"path": "app1-path",  # Adjust paths as needed
        "namespace": "argocd-kt"
      },
      {
        "name": "app2",
        #"path": "app2-path",  # Adjust paths as needed
        "namespace": "test"
      }
    ]
    EOF
