apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-plugin-script
  namespace: argocd
data:
  generate-apps.sh: |
    #!/bin/bash
    cat <<EOF
    [
      {
        "name": "app1",
        "path": "datas/git/two-git-source/git1",  # Adjust paths as needed
        "namespace": "argocd-kt"
      },
      {
        "name": "app2",
        "path": "datas/git/two-git-source/git2",  # Adjust paths as needed
        "namespace": "test"
      }
    ]
    EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm1
  namespace: argocd
data:
  configManagementPlugins: |
    - name: custom-plugin-generator
      generate:
        command: ["/bin/bash", "generate-apps.sh"]
