apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-cm
  namespace: argocd
data:
  configManagementPlugins: |
    - name: custom-plugin-generator
      generate:
        command: ["generate-apps.sh"]
