apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: "latest" # or other strategies like "tag"
spec:
  project: default
  source:
    repoURL: 'https://github.com/bitthalpatidar/test-argo.git'
    targetRevision: HEAD
    path: 'datas/test'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-kt
  syncPolicy:
