apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spin-argo-trigger
  namespace: tcbargo
  labels:
     for: kotak
     added: job
     another: label
     app.kubernetes.io/managed-by: spinnaker
     app.kubernetes.io/name: spinargoapp
  annotations:
     artifact.spinnaker.io/location: tcbargo
     artifact.spinnaker.io/name: spin-argo-trigger
     artifact.spinnaker.io/type: kubernetes/application
     moniker.spinnaker.io/application: spinargoapp
     moniker.spinnaker.io/cluster: application spin-argo-trigger
spec:
  destination:
    namespace: spin-argo-trigger
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: cm
    repoURL: 'https://github.com/gopaljayanthi/forjpmc.git'
    targetRevision: ${revision}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
