apiVersion: v1
kind: Service
metadata:
  name: {{ include "single-helm-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "single-helm-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
