replicaCount: 2

image:
  repository: postgres
  tag: "14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432
  name: postgresql

persistence:
  enabled: true
  storageClass: "standard"  # Default storage class for Minikube
  accessModes:
    - ReadWriteOnce
  size: 8Gi

resources: {}
